#
# Makefile
#
FUENTES.c=traductor.c 
INCLUDES=
CFLAGS=
SLIBS=
PROG=gcc
OPT=-Wall 

# Destino (target) especial (inicia con .)


all: traductor.c 
	$(PROG) $(OPT) traductor.c -o ctraductor 

clean:
	rm ctraductor 
